import Link from "next/link";

export const metadata = { title: "Über uns", description: "Lernen Sie die Ö&I CLEAN group GmbH und unsere Arbeitsweise kennen." };

export default function AboutPage() {
  return <main>
    <section className="page-hero"><img className="page-hero-image" src="/assets/aalen.jpg" alt="Professionelles Reinigungsteam bei der Arbeit" /><div className="container page-hero-content reveal"><div className="breadcrumb"><Link href="/">Startseite</Link><span>/</span><span>Über uns</span></div><span className="eyebrow">Seit 1997 an Ihrer Seite</span><h1>Sauberkeit, auf die Sie sich verlassen können</h1><p>Wir verbinden langjährige Erfahrung mit klaren Abläufen, persönlicher Betreuung und einem kompromisslosen Qualitätsanspruch.</p></div></section>
    <section className="section"><div className="container content-split"><div className="content-media reveal"><img src="/assets/home-cleaning.jpg" alt="Sorgfältige professionelle Reinigung" loading="lazy" /></div><div className="content-copy reveal"><span className="eyebrow dark">Ö&I CLEAN group GmbH</span><h2>Verantwortung in jedem Detail</h2><p>Seit 1997 betreuen wir Hotels, Unternehmen und Immobilien mit zuverlässigen Reinigungs- und Gebäudedienstleistungen. Dabei steht für uns nicht nur ein sauberes Ergebnis im Mittelpunkt, sondern auch eine Zusammenarbeit, die einfach funktioniert.</p><p>Unsere Teams arbeiten strukturiert, diskret und mit festen Qualitätsstandards. Dank persönlicher Ansprechpartner und flexibler Einsatzplanung reagieren wir schnell auf die Anforderungen unserer Kunden.</p><ul className="check-list"><li>Geschulte und eingespielte Reinigungsteams</li><li>Individuelle Leistungspläne statt Standardpakete</li><li>Regelmäßige Qualitätskontrollen und transparente Kommunikation</li></ul></div></div></section>
    <section className="section values"><div className="container"><div className="section-heading reveal"><span className="eyebrow dark">Unsere Werte</span><h2>Was unsere Arbeit prägt</h2><p>Vier Grundsätze bestimmen jeden Auftrag – vom ersten Gespräch bis zur laufenden Betreuung.</p></div><div className="value-grid">{[["01","Zuverlässigkeit","Vereinbarte Leistungen, Zeiten und Standards werden konsequent eingehalten."],["02","Qualität","Klare Prozesse und regelmäßige Kontrollen sichern dauerhaft gute Ergebnisse."],["03","Flexibilität","Wir passen Teams und Abläufe an Ihren Betrieb und kurzfristige Anforderungen an."],["04","Partnerschaft","Persönliche Ansprechpartner sorgen für kurze Wege und schnelle Lösungen."]].map(([number,title,text]) => <article className="value-card reveal" key={number}><span className="value-number">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="cta-band"><div className="container reveal"><div><h2>Lernen Sie uns persönlich kennen</h2><p>Wir beraten Sie unverbindlich zu einer passenden Lösung für Ihr Objekt.</p></div><Link className="button" href="/kontakt">Kontakt aufnehmen →</Link></div></section>
  </main>;
}
